apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: kemgou-awssm-external-secret
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: kemgou-awssm-secretstore
    kind: SecretStore
  target:
    name: kemgou-external-secret
    creationPolicy: Owner
  data:
  - secretKey: first
    remoteRef:
      key: my-external-secret
      property: first
  - secretKey: second
    remoteRef:
      key: my-external-secret
      property: second
