apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: kemgou-awssm-secretstore
spec:
  provider:
    aws:
      service: SecretsManager
      region: us-east-1
      auth:
        secretRef:
          accessKeyIDSecretRef:
            name: kemgou-awssm-secret
            key: access-key
          secretAccessKeySecretRef:
            name: kemgou-awssm-secret
            key: secret-access-key
